"""
Django settings for aulatrack project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path

# ============================
# RUTAS BASE
# ============================
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================
# CONFIGURACIÓN GENERAL
# ============================
SECRET_KEY = 'django-insecure-i0zs+wbc0rtgz)&-5a!ft(=slfrh29@5n5vxg3+#m@ra9dquf1'
DEBUG = True
ALLOWED_HOSTS = []


# ============================
# APLICACIONES
# ============================
INSTALLED_APPS = [
    # Apps Django base
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tu app
    'usuarios',
]


# ============================
# MODELO DE USUARIO PERSONALIZADO
# ============================
AUTH_USER_MODEL = 'usuarios.Usuario'


# ============================
# ARCHIVOS ESTÁTICOS
# ============================
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ============================
# AUTENTICACIÓN Y REDIRECCIONES
# ============================
# Estas rutas deben usar el NAMESPACE declarado en usuarios/urls.py (app_name = 'usuarios')
LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'usuarios:home_page'
LOGOUT_REDIRECT_URL = 'usuarios:login'


# ============================
# MIDDLEWARE
# ============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================
# URLS Y TEMPLATES
# ============================
ROOT_URLCONF = 'aulatrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # puedes usar una carpeta global si quieres
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aulatrack.wsgi.application'


# ============================
# BASE DE DATOS
# ============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================
# VALIDACIÓN DE CONTRASEÑAS
# ============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================
# LOCALIZACIÓN
# ============================
LANGUAGE_CODE = 'es-cl'  # 🇨🇱 idioma español de Chile
TIME_ZONE = 'America/Santiago'  # zona horaria de Chile

USE_I18N = True
USE_TZ = True


# ============================
# CONFIGURACIONES ADICIONALES
# ============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
