# Generated by Django 5.2.6 on 2025-11-12 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='usuarios.curso'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'role': 'docente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='año',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El campo 'Año' solo puede contener números.", regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(limit_choices_to={'role': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_como_profesor_jefe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='sala',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="El campo 'Sala' solo puede contener letras, números, guiones o espacios.", regex='^[A-Za-z0-9\\s-]+$')]),
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('nombre', 'curso'), name='unique_asignatura_por_curso'),
        ),
    ]
