# Generated by Django 5.2.6 on 2025-11-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_curso_asignaturas_asignatura_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'docente'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
