# Generated by Django 5.2.6 on 2025-11-20 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_asignatura_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='contacto_emergencia',
            field=models.CharField(help_text='Formato: +569XXXXXXXX', max_length=50, validators=[django.core.validators.RegexValidator(message='El número debe tener el formato chileno, por ejemplo: +56912345678', regex='^\\+?56\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Justificado', 'Justificado'), ('Atraso', 'Atraso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='sala',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="El campo 'Sala' solo puede contener letras, números, guiones o espacios.", regex='^[A-Za-z0-9\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion',
            field=models.CharField(max_length=100),
        ),
    ]
