# Generated by Django 5.2.6 on 2025-09-29 01:24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_curso_asignaturas_alter_curso_profesor_jefe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__role': 'docente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_como_profesor_jefe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('año'), django.db.models.functions.text.Lower('nombre'), django.db.models.functions.text.Lower('sala'), name='uniq_curso_anio_nombre_sala_ci'),
        ),
    ]
