# Generated by Django 5.2.6 on 2025-10-13 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_curso_profesor_jefe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellidos', 'nombres']},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='contacto_emergencia',
            field=models.CharField(help_text='Formato: +569XXXXXXXX', max_length=15, validators=[django.core.validators.RegexValidator(message='El número debe tener el formato chileno, por ejemplo: +56912345678', regex='^\\+?56\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(help_text='Formato: 12.345.678-9 o 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener un formato válido, por ejemplo: 12.345.678-9 o 12345678-9', regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[\\dkK]$')]),
        ),
    ]
