# Generated by Django 5.2.6 on 2025-10-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_alumno_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['alumno', 'asignatura', 'evaluacion']},
        ),
    ]
