# Generated by Django 5.2.6 on 2025-10-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_nota_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='numero',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
